name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for taking your time and effort for your contribution, we truly value it. 🎉'
        pr-message: 'Thank you for taking your time and effort for your contribution, we truly value it. 🎉'
